package com.dark.userdata.ntds.schema

import kotlinx.serialization.Serializable

@Serializable
enum class NodeTags(tagName: String, tagValue: String) {
    ROOT("ROOT", "TAG IS USED FOR ROOT NODE"),

    //NODES TAGS
    TOOL("Tool", "TAG REPRESENTS INTERNAL MCP TOOLS THAT ARE DESCRIBE FOR AI"),
    TEMP("Temp", "TAG IS USE TO INDICATE THAT THIS NODE HAS TEMPORARY DATA, AND THE DATA IS REMOVABLE"),
    MAIN("Main", "TAG IS USE TO INDICATE THAT THIS NODE HAS THE PERMANENT DATA AND THE DATA IS NOT REMOVABLE UNLESS THE MEMORY IS FULL"),
    AI("AI", "TAG IS USED FOR AI RELATED DATA"),

    //COMMON
    TEMP_MESSAGES("TEMP-MESSAGES", "TAG IS USED FOR RESPONSES/PROMPTS WHICH ARE SAVED FOR TEMPORARY MEMORY FOR USE"),
    MAIN_CONVERSATION("MAIN-CONVERSATION", "TAG IS USED FOR CONVERSATION WHICH HAVE BEEN SAVED IN MAIN MEMORY"),
    ASSISTANT("ASSIST", "TAG IS USED FOR ASSISTANT RELATED CONTENT LIKE ASSISTANT RESPONSE"),
    USER("USER", "TAG IS USED FOR USER RELATED CONTENT LIKE USER PROMPT"),

    //TOOLS
    APP_OPERATOR("APP_OPT", "TAG IS USED FOR APPLICATION OPERATOR TOOL"),

    //PRIORITY TAGS
    PR_LOW("PRIORITY-LOW", "THIS TAG REPRESENTS THAT THIS PARTICULAR DATA IS NOT MUCH OF A PRIORITY CAN BE BE REMOVED WHEN NEEDED"),
    PR_MEDIUM("PRIORITY-MEDIUM", "THIS TAG REPRESENTS THAT THIS PARTICULAR DATA IS OF A MEDIUM PRIORITY AND SHOULD ONLY BE REMOVED IF LOW-PRIORITY DATA IS COMPLETELY REMOVED"),
    PR_HIGH("PRIORITY-HIGH", "THIS TAG REPRESENTS THAT THIS PARTICULAR DATA IS OF A HIGH PRIORITY CAN ONLY BE REMOVED WHEN LOW-PRIORITY AND MEDIUM-PRIORITY DATA IS COMPLETELY REMOVED"),
    PR_VERY_HIGH("PRIORITY-VERY-HIGH", "THIS TAG REPRESENTS THAT THIS PARTICULAR DATA IS NOT TO BE DELETED OR REMOVED IN ANY CASE"),
}